### ISSUE TITLE
Dimensional Mirror

### ISSUE THREAD

**Issue by AlexSocol** [Extegral/Forgotten-Relics#6]
So there are some bugs with this
1. If you use it to teleport to any dimension from End it just leaves you in midair with no loaded blocks around. You need to relog to see blocks again. Sometimes after relog the game just freezes (not responding)
2. If you try to teleport TO or FROM any custom dimesion (tested with Outer Lands and Alfheim) - you will get nether portal frame spawned somewhere around zero coords

**Comment by Extegral** [comment]
I don't seem to be able to fix those issues. I already tried few ways of transfering player through dimensions while I was working on this item for the first time, and all of them had some problems with them. Most probably, the only way to fix it is making custom teleporter class, but I couldn't find any documentation or reliable guides on how to create it on 1.7.10, and all attempts I made had no success.

By now, I can only entirely disable the mirror from working iterdimensionally - there is already an option in config to do it, by the way. Or invert this option so that it's not working inderdimensionally by default, but could be enabled manually.

**Comment by AlexSocol** [comment]
Ну, в принципе, можно запретить "сбегать" из энда и просто не давать телепортироваться из него. 
Насчёт же портальной рамки - можешь использовать [вот этот метод](https://bitbucket.org/AlexSocol/alfheim/src/e24b8bf5fbeb5d7c82e4d533d73bfc2d1ebccfc0/src/main/java/alexsocol/asjlib/ASJUtilities.kt#lines-110) ([телепортер](https://bitbucket.org/AlexSocol/alfheim/src/development/src/main/java/alexsocol/asjlib/FreeTeleporter.kt)). 100%-ю надёжность не гарантирую, но, вроде, работает стабильно и без рамочек.

**Comment by Extegral** [comment]
Попробую потестить. Если сработает - будет в новом апдейте

**Comment by Extegral** [comment]
Да, это было проще чем я ожидал. Проинтегрировал телепортер в апдейте 1.7.1, теперь вроде нормально работает.
Исправить проблему с прогрузкой при телепортации из Края, похоже, не представляется возможным - но поскольку это не так существенно, я последовал согласно вашему предложению и просто убрал такую возможность. С помощью зеркала всё ещё можно попасть в Край или переместиться телепортироваться из одной точки в другую непосредственно в нём, но выбраться в другое измерение не выйдет.
